[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "GPL-3.0",
    "MIT",
    "Unicode-3.0",
]

# The confidence threshold for detecting a license from license text.
# [possible values: any between 0.0 and 1.0].
confidence-threshold = 1.0
